#define WSP_GROUP_ALL_VEHICLES_REPAIRED				0
#define WSP_GROUP_ALL_VEHICLES_TOUCHING_GROUND		1
#define WSP_GROUP_ALL_INFANTRY_MOUNTED				2
#define WSP_GROUP_ALL_CREW_MOUNTED					3
// #define WSP_GROUP_DRIVERS_ASSIGNED					4
// #define WSP_GROUP_TURRETS_ASSIGNED					5

#define WSP_GROUP_COUNT 4