#include "..\..\common.hpp"

ADD_LOADOUT("GM_WG_SL",	 			"GM_WestGer\WestGer\GM_WG_SL.sqf"			)
ADD_LOADOUT("GM_WG_TL", 			"GM_WestGer\WestGer\GM_WG_SL.sqf"			)
ADD_LOADOUT("GM_WG_Officer", 		"GM_WestGer\WestGer\GM_WG_Officer.sqf"		)
ADD_LOADOUT("GM_WG_GL",	 	 		"GM_WestGer\WestGer\GM_WG_GL.sqf"			)
ADD_LOADOUT("GM_WG_Rifleman",	 	"GM_WestGer\WestGer\GM_WG_Rifleman.sqf"		)
ADD_LOADOUT("GM_WG_Marksman",    	"GM_WestGer\WestGer\GM_WG_Marksman.sqf"		)
ADD_LOADOUT("GM_WG_Sniper",	 		"GM_WestGer\WestGer\GM_WG_Sniper.sqf"		)
ADD_LOADOUT("GM_WG_Spotter", 		"GM_WestGer\WestGer\GM_WG_Spotter.sqf"		)
ADD_LOADOUT("GM_WG_Demolition", 	"GM_WestGer\WestGer\GM_WG_Demolition.sqf"	)
ADD_LOADOUT("GM_WG_AmmoBearer", 	"GM_WestGer\WestGer\GM_WG_AmmoBearer.sqf"	)
ADD_LOADOUT("GM_WG_LAT",	     	"GM_WestGer\WestGer\GM_WG_LAT.sqf"			)
ADD_LOADOUT("GM_WG_AT", 		 	"GM_WestGer\WestGer\GM_WG_AT.sqf"			)
ADD_LOADOUT("GM_WG_AA", 		 	"GM_WestGer\WestGer\GM_WG_AA.sqf"			)
ADD_LOADOUT("GM_WG_Pilot", 		 	"GM_WestGer\WestGer\GM_WG_Pilot.sqf"			)
ADD_LOADOUT("GM_WG_MG", 			"GM_WestGer\WestGer\GM_WG_MG.sqf"			)
ADD_LOADOUT("GM_WG_Medic", 			"GM_WestGer\WestGer\GM_WG_Medic.sqf"		)
ADD_LOADOUT("GM_WG_Engineer", 		"GM_WestGer\WestGer\GM_WG_Engineer.sqf"		)
ADD_LOADOUT("GM_WG_Crew", 			"GM_WestGer\WestGer\GM_WG_Crew.sqf"			)
ADD_LOADOUT("GM_WG_Unarmed", 		"GM_WestGer\WestGer\GM_WG_Unarmed.sqf"		)