removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

_RandomVest = selectRandom ["FGN_AAF_CIRAS_TL","FGN_AAF_CIRAS_TL_CamB"];
this addVest _RandomVest;
_RandomHeadgear = selectRandom ["FGN_AAF_Boonie_Type07","rhsusf_opscore_mar_ut","rhsusf_opscore_mar_ut_pelt"];
this addHeadgear _RandomHeadgear;
_RandomGoggles = selectRandom ["FGN_AAF_Shemag_tan","FGN_AAF_Shemag","rhs_scarf","rhsusf_oakley_goggles_blk","",""];
this addGoggles _RandomGoggles;
this forceaddUniform "rhs_uniform_gorka_1_a";
this addBackpack "FGN_AAF_Bergen_SL_Type07";

this addWeapon "rhs_weap_mk18_KAC_bk";
this addPrimaryWeaponItem "rhsusf_acc_rotex5_grey";
_RandomSight = selectRandom ["rhsusf_acc_eotech_xps3", "rhsusf_acc_g33_xps3", "rhsusf_acc_su230", "rhsusf_acc_su230_mrds"];
this addPrimaryWeaponItem _RandomSight;
_RandomGrip = selectRandom ["rhsusf_acc_grip1", "rhsusf_acc_grip2", "rhsusf_acc_kac_grip", "", ""];
this addPrimaryWeaponItem _RandomGrip;
_RandomLaser = selectRandom ["rhsusf_acc_anpeq15side_bk", "rhsusf_acc_anpeq15_bk_top", "rhsusf_acc_anpeq15_bk_light"];
this addPrimaryWeaponItem _RandomLaser;
this addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
this addWeapon "rhs_weap_rpg75";
this addWeapon "rhsusf_weap_glock17g4";
this addHandgunItem "rhsusf_acc_omega9k";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "rhsusf_mag_17Rnd_9x19_JHP";
this addWeapon "Binocular";

this addItemToUniform "FirstAidKit";
this addItemToUniform "optic_NVS";
for "_i" from 1 to 2 do {this addItemToUniform "rhsusf_mag_17Rnd_9x19_JHP";};
this addItemToVest "rhs_grenade_anm8_mag";
this addItemToVest "rhs_grenade_m15_mag";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_mk3a2";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m14_th3";};
this addItemToVest "I_IR_Grenade";
this addItemToBackpack "rhs_mag_nspd";
this addItemToBackpack "rhs_mag_nspn_green";
this addItemToBackpack "rhs_mag_nspn_red";
this addItemToBackpack "rhs_mag_nspn_yellow";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles_OPFOR";