#include "..\..\common.hpp"

ADD_LOADOUT("WW2_UK_recon_AT",			"WW2_UK\UK_Recon\UK_recon_AT.sqf")
ADD_LOADOUT("WW2_UK_recon_explosives",	"WW2_UK\UK_Recon\UK_recon_explosives.sqf")
ADD_LOADOUT("WW2_UK_recon_JTAC",		"WW2_UK\UK_Recon\UK_recon_JTAC.sqf")
ADD_LOADOUT("WW2_UK_recon_marksman",	"WW2_UK\UK_Recon\UK_recon_marksman.sqf")
ADD_LOADOUT("WW2_UK_recon_medic",		"WW2_UK\UK_Recon\UK_recon_medic.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman",	"WW2_UK\UK_Recon\UK_recon_rifleman.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_2",	"WW2_UK\UK_Recon\UK_recon_rifleman_2.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_3",	"WW2_UK\UK_Recon\UK_recon_rifleman_3.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_4",	"WW2_UK\UK_Recon\UK_recon_rifleman_4.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_5",	"WW2_UK\UK_Recon\UK_recon_rifleman_5.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_6",	"WW2_UK\UK_Recon\UK_recon_rifleman_6.sqf")
ADD_LOADOUT("WW2_UK_recon_rifleman_7",	"WW2_UK\UK_Recon\UK_recon_rifleman_7.sqf")
ADD_LOADOUT("WW2_UK_recon_TL",			"WW2_UK\UK_Recon\UK_recon_TL.sqf")
