#include "..\common.hpp"

ADD_LOADOUT("GM_CIVILIAN_1",			"GM_CIVILIAN\GM_CIVILIAN_1.sqf")
ADD_LOADOUT("GM_CIVILIAN_Militant_1",	"GM_CIVILIAN\GM_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("GM_CIVILIAN_Saboteur_1",	"GM_CIVILIAN\GM_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("GM_PLAYER_1",				"GM_CIVILIAN\GM_PLAYER_1.sqf")