
#define GARRISON_TYPE_GENERAL		"general"
#define GARRISON_TYPE_AIR			"air"
#define GARRISON_TYPE_PLAYER		"player"
#define GARRISON_TYPES_ALL			[GARRISON_TYPE_GENERAL, GARRISON_TYPE_AIR, GARRISON_TYPE_PLAYER]