#include "..\..\common.hpp"

ADD_LOADOUT("B_APC_Wheeled_01_cannon_F_1",			"Arma3_NATO\NATO\B_APC_Wheeled_01_cannon_F_1.sqf")
ADD_LOADOUT("B_APC_Wheeled_01_cannon_F_2",			"Arma3_NATO\NATO\B_APC_Wheeled_01_cannon_F_2.sqf")
ADD_LOADOUT("B_APC_Wheeled_01_cannon_F_3",			"Arma3_NATO\NATO\B_APC_Wheeled_01_cannon_F_3.sqf")
ADD_LOADOUT("B_APC_Wheeled_01_cannon_F_4",			"Arma3_NATO\NATO\B_APC_Wheeled_01_cannon_F_4.sqf")
ADD_LOADOUT("B_APC_Tracked_01_CRV_F_1",			"Arma3_NATO\NATO\B_APC_Tracked_01_CRV_F_1.sqf")
ADD_LOADOUT("B_APC_Tracked_01_rcws_F_1",			"Arma3_NATO\NATO\B_APC_Tracked_01_rcws_F_1.sqf")
ADD_LOADOUT("B_MBT_01_cannon_F_1",			"Arma3_NATO\NATO\B_MBT_01_cannon_F_1.sqf")
ADD_LOADOUT("B_MBT_01_cannon_F_2",			"Arma3_NATO\NATO\B_MBT_01_cannon_F_2.sqf")
ADD_LOADOUT("B_MBT_01_TUSK_F_1",			"Arma3_NATO\NATO\B_MBT_01_TUSK_F_1.sqf")
ADD_LOADOUT("B_MBT_01_TUSK_F_2",			"Arma3_NATO\NATO\B_MBT_01_TUSK_F_2.sqf")
ADD_LOADOUT("B_AFV_Wheeled_01_cannon_F_1",			"Arma3_NATO\NATO\B_AFV_Wheeled_01_cannon_F_1.sqf")
ADD_LOADOUT("B_AFV_Wheeled_01_cannon_F_2",			"Arma3_NATO\NATO\B_AFV_Wheeled_01_cannon_F_2.sqf")
ADD_LOADOUT("B_AFV_Wheeled_01_up_cannon_F_1",			"Arma3_NATO\NATO\B_AFV_Wheeled_01_up_cannon_F_1.sqf")
ADD_LOADOUT("B_AFV_Wheeled_01_up_cannon_F_2",			"Arma3_NATO\NATO\B_AFV_Wheeled_01_up_cannon_F_2.sqf")