#include "..\common.hpp"

ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_1",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_1.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_2",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_2.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_3",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_3.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_4",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_4.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_5",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_5.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_6",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_6.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_7",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_7.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_8",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_8.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_9",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_9.sqf")
ADD_LOADOUT("UK3CB_BAF_Ammo_MTP_10",		"3CB_BAF\UK3CB_BAF_Ammo_MTP_10.sqf")