g_phrasesCantTalkBusy = [
	"STR_CANT_TALK_BUSY_1",
	"STR_CANT_TALK_BUSY_2",
	"STR_CANT_TALK_BUSY_3",
	"STR_CANT_TALK_BUSY_4",
	"STR_CANT_TALK_BUSY_5",
	"STR_CANT_TALK_BUSY_6",
	"STR_CANT_TALK_BUSY_7"
];

g_phrasesCantTalkAnyMore = [
	"STR_CANT_TALK_ANYMORE_1",
	"STR_CANT_TALK_ANYMORE_2",
	"STR_CANT_TALK_ANYMORE_3",
	"STR_CANT_TALK_ANYMORE_4",
	"STR_CANT_TALK_ANYMORE_5",
	"STR_CANT_TALK_ANYMORE_6",
	"STR_CANT_TALK_ANYMORE_7",
	"STR_CANT_TALK_ANYMORE_8",
	"STR_CANT_TALK_ANYMORE_9"
];

g_phrasesCivilianCantTalkScared = [
	"STR_CANT_TALK_Scared_1",
	"STR_CANT_TALK_Scared_2",
	"STR_CANT_TALK_Scared_3",
	"STR_CANT_TALK_Scared_4",
	"STR_CANT_TALK_Scared_5",
	"STR_CANT_TALK_Scared_6",
	"STR_CANT_TALK_Scared_7"
];

g_phasesCivilianPanic = [
	"STR_C_PANIC_1",
	"STR_C_PANIC_2",
	"STR_C_PANIC_3",
	"STR_C_PANIC_4",
	"STR_C_PANIC_5",
	"STR_C_PANIC_6",
	"STR_C_PANIC_7",
	"STR_C_PANIC_8",
	"STR_C_PANIC_9",
	"STR_C_PANIC_10",
	"STR_C_PANIC_11",
	"STR_C_PANIC_12",
	"STR_C_PANIC_13",
	"STR_C_PANIC_14",
	"STR_C_PANIC_15",
	"STR_C_PANIC_16",
	"STR_C_PANIC_17",
	"STR_C_PANIC_18",
	"STR_C_PANIC_19"
];

g_phrasesPlayerStartDialogue = [
	"STR_START_DIALOGUE_1",
	"STR_START_DIALOGUE_2",
	"STR_START_DIALOGUE_3",
	"STR_START_DIALOGUE_4",
	"STR_START_DIALOGUE_5",
	"STR_START_DIALOGUE_6",
	"STR_START_DIALOGUE_7",
	"STR_START_DIALOGUE_8",
	"STR_START_DIALOGUE_9",
	"STR_START_DIALOGUE_10"
];

g_phrasesCivilianNonsense = [
	"STR_C_NONSENSE_1",
	"STR_C_NONSENSE_2",
	"STR_C_NONSENSE_3",
	"STR_C_NONSENSE_4",
	"STR_C_NONSENSE_5",
	"STR_C_NONSENSE_6",
	"STR_C_NONSENSE_7",
	"STR_C_NONSENSE_8",
	"STR_C_NONSENSE_9",
	"STR_C_NONSENSE_10"
];

g_phrasesCivilianCantTalkArrested = [
	"STR_C_CANT_TALK_ARRESTED_1",
	"STR_C_CANT_TALK_ARRESTED_2",
	"STR_C_CANT_TALK_ARRESTED_3",
	"STR_C_CANT_TALK_ARRESTED_4",
	"STR_C_CANT_TALK_ARRESTED_5",
	"STR_C_CANT_TALK_ARRESTED_6"
];

// Player was untied by player
g_phrasesPlayerUntied = [
	"STR_P_UNTIED_1",
	"STR_P_UNTIED_2"
];

// Civilian was untied by player
g_phrasesCivilianUntied = [
	"STR_C_UNTIED_1",
	"STR_C_UNTIED_2"
];
