{#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"
#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\OOP_Light\OOP_Light.h"



























































































































































































































































































































#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Message\Message.hpp"





































#line 2 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Action\Action.hpp"






#line 3 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\MessageTypes.hpp"
































#line 4 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\GlobalAssert.hpp"




#line 5 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Stimulus\Stimulus.hpp"

















































#line 6 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\WorldFact\WorldFact.hpp"














































#line 7 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\stimulusTypes.hpp"












#line 8 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\worldFactTypes.hpp"


#line 9 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Group\Group.hpp"



























#line 10 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\garrisonWorldStateProperties.hpp"





























































#line 11 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf"










[] call { scopeName "scopeClass"; private _oop_classNameStr = "ActionGarrisonRelax"; missionNameSpace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "nextID")),  0]; private _oop_memList = []; private _oop_staticMemList = []; private _oop_parents = []; private _oop_methodList = []; if ( "Action" != "") then { 	if (!([ "Action", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 21] call OOP_assert_class)) then {breakOut "scopeClass";}; 	_oop_parents = +( missionNameSpace getVariable ("o_" + ( "Action") + "_spm_" + (  "parents")) ); _oop_parents pushBackUnique  "Action"; 	_oop_memList = +( missionNameSpace getVariable ("o_" + ( "Action") + "_spm_" + (  "memList")) ); 	_oop_staticMemList = +( missionNameSpace getVariable ("o_" + ( "Action") + "_spm_" + (  "staticMemList")) ); 	_oop_methodList = +( missionNameSpace getVariable ("o_" + ( "Action") + "_spm_" + (  "methodList")) ); 	private _oop_topParent = _oop_parents select ((count _oop_parents) - 1); 	{ private _oop_methodCode = ( missionNameSpace getVariable ((_oop_topParent) + "_fnc_" + (  _x)) ); 	missionNameSpace setVariable [(("ActionGarrisonRelax") + "_fnc_" + (  _x)),  _oop_methodCode]; 	} forEach (_oop_methodList - ["new", "delete", "copy"]); }; missionNameSpace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "parents")),  _oop_parents]; missionNameSpace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "memList")),  _oop_memList]; missionNameSpace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "staticMemList")),  _oop_staticMemList]; missionNameSpace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "methodList")),  _oop_methodList]; _oop_methodList pushBackUnique "new"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "new")), {} ]; _oop_methodList pushBackUnique "delete"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "delete")), {} ]; _oop_methodList pushBackUnique "copy"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "copy")), {} ]; _oop_memList pushBackUnique "oop_parent";










_oop_methodList pushBackUnique "activate"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "activate")), {
params [["_thisObject", "", [""]]];		



private _AI = ( if([_thisObject,    "AI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 36] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +      "AI") )}else{nil} );
private _gar = ( if([_AI,    "agent", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 37] call OOP_assert_member) then {( missionNameSpace getVariable ((_AI) + "_" +      "agent") )}else{nil} );
private _patrolGroups = ([_gar,   			4]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 38] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} );

{
private _groupAI = ([_x]) call ( if([(( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") )),    "getAI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 41] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") ))) + "_fnc_" + (     "getAI")) )}else{nil} );
if (!isNil "_AI") then {
if (_AI != "") then {

private _args = ["GoalGroupPatrol", 0, [], ( if([_thisObject,    "AI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 45] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +      "AI") )}else{nil} )];
([_groupAI,   "addExternalGoal",   _args]) call ( if([(( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") )),    "postMethodAsync", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 46] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") ))) + "_fnc_" + (     "postMethodAsync")) )}else{nil} );
};
};
} forEach _patrolGroups;


if([_thisObject,    "state", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 52] call OOP_assert_member) then {missionNameSpace setVariable [((_thisObject) + "_" +      "state"),     		0]};


		0

} ];


_oop_methodList pushBackUnique "process"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "process")), {
params [["_thisObject", "", [""]]];

([_thisObject] +   []) call ( if([(( missionNameSpace getVariable ((_thisObject) + "_" +   "oop_parent") )),    "activateIfInactive", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 63] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_thisObject) + "_" +   "oop_parent") ))) + "_fnc_" + (     "activateIfInactive")) )}else{nil} );


		0
} ];


_oop_methodList pushBackUnique "terminate"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "terminate")), {
params [["_thisObject", "", [""]]];


private _AI = ( if([_thisObject,    "AI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 74] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +      "AI") )}else{nil} );
private _gar = ( if([_AI,    "agent", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 75] call OOP_assert_member) then {( missionNameSpace getVariable ((_AI) + "_" +      "agent") )}else{nil} );
private _patrolGroups = ([_gar,   			4]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 76] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} );

{
private _groupAI = ([_x]) call ( if([(( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") )),    "getAI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 79] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") ))) + "_fnc_" + (     "getAI")) )}else{nil} );
if (!isNil "_AI") then {
if (_AI != "") then {
private _args = ["GoalGroupPatrol", ""];
([_groupAI,   "deleteExternalGoal",   _args]) call ( if([(( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") )),    "postMethodAsync", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonRelax.sqf", 83] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") ))) + "_fnc_" + (     "postMethodAsync")) )}else{nil} );
};
};
} forEach _patrolGroups;

} ];

};}