{#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf"







#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\OOP_Light\OOP_Light.h"




































































































































































































































































#line 3 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf"


[] call { scopeName "scopeClass"; private _oop_classNameStr = "Garrison"; missionNameSpace setVariable [("o_" + _oop_classNameStr + "_spm_" +   "nextID"),  0]; private _oop_memList = []; private _oop_staticMemList = []; private _oop_parents = []; private _oop_methodList = []; if ( "MessageReceiver" != "") then { 	if (!([ "MessageReceiver", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf", 10] call OOP_assert_class)) then {breakOut "scopeClass";}; 	_oop_parents = +( missionNameSpace getVariable ("o_" +  "MessageReceiver" + "_spm_" +   "parents") ); _oop_parents pushBackUnique  "MessageReceiver"; 	_oop_memList = +( missionNameSpace getVariable ("o_" +  "MessageReceiver" + "_spm_" +   "memList") ); 	_oop_staticMemList = +( missionNameSpace getVariable ("o_" +  "MessageReceiver" + "_spm_" +   "staticMemList") ); 	_oop_methodList = +( missionNameSpace getVariable ("o_" +  "MessageReceiver" + "_spm_" +   "methodList") ); 	private _oop_topParent = _oop_parents select ((count _oop_parents) - 1); 	{ private _oop_methodCode = ( missionNameSpace getVariable (_oop_topParent + "_fnc_" +   _x) ); 	missionNameSpace setVariable [("Garrison" + "_fnc_" +   _x),  _oop_methodCode]; 	} forEach (_oop_methodList - ["new", "delete", "copy"]); }; missionNameSpace setVariable [("o_" + _oop_classNameStr + "_spm_" +   "parents"),  _oop_parents]; missionNameSpace setVariable [("o_" + _oop_classNameStr + "_spm_" +   "memList"),  _oop_memList]; missionNameSpace setVariable [("o_" + _oop_classNameStr + "_spm_" +   "staticMemList"),  _oop_staticMemList]; missionNameSpace setVariable [("o_" + _oop_classNameStr + "_spm_" +   "methodList"),  _oop_methodList]; _oop_methodList pushBackUnique "new"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "new"), {} ]; _oop_methodList pushBackUnique "delete"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "delete"), {} ]; _oop_methodList pushBackUnique "copy"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "copy"), {} ]; _oop_memList pushBackUnique "oop_parent";

_oop_memList pushBackUnique "units";
_oop_memList pushBackUnique "groups";





_oop_methodList pushBackUnique "new"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "new"), {
params [["_thisObject", "", [""]]];
if([_thisObject,   "units", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf", 20] call OOP_assert_member) then {missionNameSpace setVariable [(_thisObject + "_" +     "units"),    []]};
if([_thisObject,   "groups", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf", 21] call OOP_assert_member) then {missionNameSpace setVariable [(_thisObject + "_" +     "groups"),    []]};
} ];





_oop_methodList pushBackUnique "delete"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "delete"), {
params [["_thisObject", "", [""]]];
if([_thisObject,   "units", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf", 30] call OOP_assert_member) then {missionNameSpace setVariable [(_thisObject + "_" +     "units"),    nil]};
if([_thisObject,   "groups", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Garrison\Garrison.sqf", 31] call OOP_assert_member) then {missionNameSpace setVariable [(_thisObject + "_" +     "groups"),    nil]};		
} ];

_oop_methodList pushBackUnique "spawn"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "spawn"), compile preprocessFileLineNumbers  "Garrison\spawn.sqf"];

_oop_methodList pushBackUnique "despawn"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "despawn"), compile preprocessFileLineNumbers  "Garrison\despawn.sqf"];

_oop_methodList pushBackUnique "addUnit"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "addUnit"), compile preprocessFileLineNumbers  "Garrison\addUnit.sqf"];

_oop_methodList pushBackUnique "moveUnit"; missionNameSpace setVariable [(_oop_classNameStr + "_fnc_" +  "moveUnit"), compile preprocessFileLineNumbers  "Garrison\moveUnit.sqf"];

};}