{#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"
#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\OOP_Light\OOP_Light.h"

























































































































































































































































































































































































































































#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Message\Message.hpp"































































#line 2 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Action\Action.hpp"

















#line 3 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\MessageTypes.hpp"
































#line 4 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\GlobalAssert.hpp"




#line 5 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Stimulus\Stimulus.hpp"































































#line 6 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\WorldFact\WorldFact.hpp"


























































#line 7 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\stimulusTypes.hpp"



















#line 8 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\worldFactTypes.hpp"




#line 9 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\garrisonWorldStateProperties.hpp"
































































#line 10 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\parameterTags.hpp"

















#line 11 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"

#line 1 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\Group\Group.hpp"


































#line 12 "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf"










[] call { scopeName "scopeClass"; private _oop_classNameStr = "ActionGarrisonMountCrew"; missionNamespace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "nextID")),  0]; private _oop_memList = []; private _oop_staticMemList = []; private _oop_parents = []; private _oop_methodList = []; if ( "ActionGarrison" != "") then { 	if (!([ "ActionGarrison", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 22] call OOP_assert_class)) then {breakOut "scopeClass";}; 	_oop_parents = +( missionNamespace getVariable ("o_" + ( "ActionGarrison") + "_spm_" + (  "parents")) ); _oop_parents pushBackUnique  "ActionGarrison"; 	_oop_memList = +( missionNamespace getVariable ("o_" + ( "ActionGarrison") + "_spm_" + (  "memList")) ); 	_oop_staticMemList = +( missionNamespace getVariable ("o_" + ( "ActionGarrison") + "_spm_" + (  "staticMemList")) ); 	_oop_methodList = +( missionNamespace getVariable ("o_" + ( "ActionGarrison") + "_spm_" + (  "methodList")) ); 	private _oop_topParent = _oop_parents select ((count _oop_parents) - 1); 	{ private _oop_methodCode = ( missionNameSpace getVariable ((_oop_topParent) + "_fnc_" + (  _x)) ); 	missionNamespace setVariable [(("ActionGarrisonMountCrew") + "_fnc_" + (  _x)),  _oop_methodCode]; 	} forEach (_oop_methodList - ["new", "delete", "copy"]); }; missionNamespace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "parents")),  _oop_parents]; missionNamespace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "memList")),  _oop_memList]; missionNamespace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "staticMemList")),  _oop_staticMemList]; missionNamespace setVariable [("o_" + (_oop_classNameStr) + "_spm_" + (  "methodList")),  _oop_methodList]; _oop_methodList pushBackUnique "new"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "new")), {} ]; _oop_methodList pushBackUnique "delete"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "delete")), {} ]; _oop_methodList pushBackUnique "copy"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "copy")), {} ]; _oop_memList pushBackUnique "oop_parent"; _oop_memList pushBackUnique "oop_public";

_oop_memList pushBackUnique "mount"; 



_oop_methodList pushBackUnique "new"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "new")), {
params [["_thisObject", "", [""]], ["_AI", "", [""]], ["_parameters", [], [[]]] ];

private _mount = ((["Action",   _parameters,   "g_mount"]) call ( if(["Action",    "getParameterValue", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 30] call OOP_assert_method) then {( missionNameSpace getVariable (("Action") + "_fnc_" + (     "getParameterValue")) )}else{nil} ));;
if([_thisObject,   "mount", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 31] call OOP_assert_member) then {missionNameSpace setVariable [((_thisObject) + "_" +     "mount"),     _mount]};
} ];


_oop_methodList pushBackUnique "activate"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "activate")), {
params [["_to", "", [""]]];		

private _gar = ( if([_thisObject,   "gar", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 38] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "gar") )}else{nil} );
private _AI = ( if([_thisObject,   "AI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 39] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "AI") )}else{nil} );
private _mount = ( if([_thisObject,   "mount", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 40] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "mount") )}else{nil} );

private _vehGroups = (([_gar,   	2]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 42] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} )) + (([_gar,   1]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 42] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} ));


if (_mount) then {
{

private _groupAI = (([_x]) call ( if([(( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") )),    "getAI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 48] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_x) + "_" +   "oop_parent") ))) + "_fnc_" + (     "getAI")) )}else{nil} ));
(([_groupAI,   "GoalGroupGetInVehiclesAsCrew",   0,   [],   _AI]) call ( if([(( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") )),    "addExternalGoal", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 49] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_groupAI) + "_" +   "oop_parent") ))) + "_fnc_" + (     "addExternalGoal")) )}else{nil} ));
} forEach _vehGroups;
} else {

};


if([_thisObject,    "state", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 56] call OOP_assert_member) then {missionNameSpace setVariable [((_thisObject) + "_" +      "state"),     		0]};


		0

} ];


_oop_methodList pushBackUnique "process"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "process")), {
params [["_thisObject", "", [""]]];

private _state = (([_thisObject] +   []) call ( if([(( missionNameSpace getVariable ((_thisObject) + "_" +   "oop_parent") )),    "activateIfInactive", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 67] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_thisObject) + "_" +   "oop_parent") ))) + "_fnc_" + (     "activateIfInactive")) )}else{nil} ));

scopeName "s0";

if (_state == 		0) then {
private _gar = ( if([_thisObject,   "gar", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 72] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "gar") )}else{nil} );
private _AI = ( if([_thisObject,   "AI", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 73] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "AI") )}else{nil} );
private _mount = ( if([_thisObject,   "mount", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 74] call OOP_assert_member) then {( missionNameSpace getVariable ((_thisObject) + "_" +     "mount") )}else{nil} );
private _vehGroups = (([_gar,   	2]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 75] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} )) + (([_gar,   1]) call ( if([(( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") )),    "findGroupsByType", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 75] call OOP_assert_method) then {( missionNameSpace getVariable (((( missionNameSpace getVariable ((_gar) + "_" +   "oop_parent") ))) + "_fnc_" + (     "findGroupsByType")) )}else{nil} ));


if (_mount) then {

if (((["AI",   "GoalGroupGetInVehiclesAsCrew",   _AI]) call ( if(["AI",    "anyAgentFailedExternalGoal", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 80] call OOP_assert_method) then {( missionNameSpace getVariable (("AI") + "_fnc_" + (     "anyAgentFailedExternalGoal")) )}else{nil} ));) then {
_state = 		3;
breakTo "s0";
};


if (((["AI",   "GoalGroupGetInVehiclesAsCrew",   _AI]) call ( if(["AI",    "allAgentsCompletedExternalGoal", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 86] call OOP_assert_method) then {( missionNameSpace getVariable (("AI") + "_fnc_" + (     "allAgentsCompletedExternalGoal")) )}else{nil} ));) then {
_state = 	2;
breakTo "s0";
};
} else {

};
};

if([_thisObject,   "state", "C:\Users\s-tron\Documents\Arma 3 - Other Profiles\Sparker\missions\Project_0\Project_0.Stratis\AI\Garrison\ActionGarrisonMountCrew.sqf", 95] call OOP_assert_member) then {missionNameSpace setVariable [((_thisObject) + "_" +     "state"),     _state]};
_state
} ];


_oop_methodList pushBackUnique "terminate"; missionNameSpace setVariable [((_oop_classNameStr) + "_fnc_" + ( "terminate")), {
params [["_thisObject", "", [""]]];
} ]; 

};}