#include "..\common.hpp"

ADD_LOADOUT("Arma3_CIVILIAN_Default",		"Arma3_CIVILIAN\A3_CIVILIAN_Default.sqf")
ADD_LOADOUT("Arma3_CIVILIAN_1",				"Arma3_CIVILIAN\A3_CIVILIAN_1.sqf")
ADD_LOADOUT("Arma3_CIVILIAN_Militant_1",	"Arma3_CIVILIAN\A3_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("Arma3_CIVILIAN_Saboteur_1",	"Arma3_CIVILIAN\A3_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("Arma3_PLAYER_1",				"Arma3_CIVILIAN\A3_PLAYER_1.sqf")
ADD_LOADOUT("Arma3_PLAYER_1_RHS",				"Arma3_CIVILIAN\A3_PLAYER_1_RHS.sqf")
ADD_LOADOUT("Arma3_PLAYER_2",				"Arma3_CIVILIAN\A3_PLAYER_1_Small_Arms.sqf")
ADD_LOADOUT("Arma3_CIVILIAN_Militant_2",				"Arma3_CIVILIAN\A3_CIVILIAN_Militant_1_Small_Arms.sqf")
ADD_LOADOUT("Arma3_CIVILIAN_Default_2",				"Arma3_CIVILIAN\A3_CIVILIAN_Default_Small_Arms.sqf")