#include "..\common.hpp"

ADD_LOADOUT("SPE_CIVILIAN_IFA3_Default",		"SPE_CIVILIAN_IFA3\SPE_CIVILIAN_IFA3_Default.sqf")
ADD_LOADOUT("SPE_CIVILIAN_IFA3_1",				"SPE_CIVILIAN_IFA3\SPE_CIVILIAN_IFA3_1.sqf")
ADD_LOADOUT("SPE_CIVILIAN_IFA3_Militant_1",		"SPE_CIVILIAN_IFA3\SPE_CIVILIAN_IFA3_Militant_1.sqf")
ADD_LOADOUT("SPE_CIVILIAN_IFA3_Saboteur_1",		"SPE_CIVILIAN_IFA3\SPE_CIVILIAN_IFA3_Saboteur_1.sqf")
ADD_LOADOUT("SPE_PLAYER_IFA3_1",				"SPE_CIVILIAN_IFA3\SPE_PLAYER_IFA3_1.sqf")
