#include "..\defineCommon.inc"

#define EMPTY_ARRAY [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]



//STRINGS ACTIONS

#define STR_ACTION_ICON_ARSENAL "\A3\ui_f\data\GUI\Rsc\RscDisplayArsenal\spaceArsenal_ca.paa"
#define STR_ACTION_TEXT_ARSENAL localize "STR_JNA_ACT_OPEN"

#define STR_ACTION_ICON_ARSENAL_CONTAINER "\A3\ui_f\data\GUI\Rsc\RscDisplayArsenal\spaceArsenal_ca.paa" //TODO
#define STR_ACTION_TEXT_ARSENAL_CONTAINER localize "STR_JNA_ACT_CONTAINER_OPEN"

#define STR_ACTION_ICON_ARSENAL_UNLOAD "\A3\ui_f\data\GUI\Rsc\RscDisplayArsenal\spaceArsenal_ca.paa" //TODO
#define STR_ACTION_TEXT_ARSENAL_UNLOAD localize "STR_JNA_ACT_UNLOAD"

