#include "..\..\common.hpp"

ADD_LOADOUT("Arma3_AAF_HMG",		"Arma3_AAF\AAF\A3_AAF_HMG.sqf")
ADD_LOADOUT("Arma3_AAF_sniper",		"Arma3_AAF\AAF\A3_AAF_sniper.sqf")
ADD_LOADOUT("Arma3_AAF_spotter",	"Arma3_AAF\AAF\A3_AAF_spotter.sqf")
ADD_LOADOUT("A3_AAF_offroad_unarmed",	"Arma3_AAF\AAF\A3_AAF_offroad_unarmed.sqf")
ADD_LOADOUT("I_G_Offroad_01_armed_F_1",	"Arma3_AAF\AAF\I_G_Offroad_01_armed_F_1.sqf")
ADD_LOADOUT("I_APC_tracked_03_cannon_F_1",	"Arma3_AAF\AAF\I_APC_tracked_03_cannon_F_1.sqf")
ADD_LOADOUT("I_APC_tracked_03_cannon_F_2",	"Arma3_AAF\AAF\I_APC_tracked_03_cannon_F_2.sqf")
ADD_LOADOUT("I_APC_tracked_03_cannon_F_3",	"Arma3_AAF\AAF\I_APC_tracked_03_cannon_F_3.sqf")
ADD_LOADOUT("I_APC_tracked_03_cannon_F_4",	"Arma3_AAF\AAF\I_APC_tracked_03_cannon_F_4.sqf")
ADD_LOADOUT("I_APC_Wheeled_03_cannon_F_1",	"Arma3_AAF\AAF\I_APC_Wheeled_03_cannon_F_1.sqf")
ADD_LOADOUT("I_MBT_03_cannon_F_1",	"Arma3_AAF\AAF\I_MBT_03_cannon_F_1.sqf")
ADD_LOADOUT("I_MBT_03_cannon_F_2",	"Arma3_AAF\AAF\I_MBT_03_cannon_F_2.sqf")
ADD_LOADOUT("I_MBT_03_cannon_F_3",	"Arma3_AAF\AAF\I_MBT_03_cannon_F_3.sqf")
ADD_LOADOUT("I_MBT_03_cannon_F_4",	"Arma3_AAF\AAF\I_MBT_03_cannon_F_4.sqf")
