#include "..\common.hpp"

ADD_LOADOUT("SPE_IFA3_CIVILIAN_Default",		"SPE_IFA3_CIVILIAN\SPE_IFA3_CIVILIAN_Default.sqf")
ADD_LOADOUT("SPE_IFA3_CIVILIAN_1",				"SPE_IFA3_CIVILIAN\SPE_IFA3_CIVILIAN_1.sqf")
ADD_LOADOUT("SPE_IFA3_CIVILIAN_Militant_1",		"SPE_IFA3_CIVILIAN\SPE_IFA3_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("SPE_IFA3_CIVILIAN_Saboteur_1",		"SPE_IFA3_CIVILIAN\SPE_IFA3_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("SPE_IFA3_PLAYER_1",				"SPE_IFA3_CIVILIAN\SPE_IFA3_PLAYER_1.sqf")
