#define OOP_INFO
#define OOP_ERROR
#define OOP_WARNING
#define OOP_DEBUG
#define OFSTREAM_FILE "AI.rpt"
#include "..\..\common.h"
#include "..\..\Message\Message.hpp"
#include "..\Action\Action.hpp"
#include "..\..\MessageTypes.hpp"
#include "..\..\defineCommon.inc"
#include "..\Stimulus\Stimulus.hpp"
#include "..\WorldFact\WorldFact.hpp"
#include "..\stimulusTypes.hpp"
#include "..\worldFactTypes.hpp"
#include "..\parameterTags.hpp"
#include "..\..\Group\Group.hpp"
#include "..\..\Unit\Unit.hpp"
#include "..\targetStruct.hpp"
#include "..\Garrison\garrisonWorldStateProperties.hpp"
#include "groupWorldStateProperties.hpp"
#include "..\..\Location\Location.hpp"
#include "..\..\MessageReceiver\MessageReceiver.hpp"