// Auto generated file
call compile preprocessFileLineNumbers "AI\Group\AIGroup.sqf";
call compile preprocessFileLineNumbers "AI\Group\_ActionGroup.sqf";
call compile preprocessFileLineNumbers "AI\Group\ActionGroupPatrol.sqf";
call compile preprocessFileLineNumbers "AI\Group\ActionGroupRelax.sqf";
call compile preprocessFileLineNumbers "AI\Group\GoalGroupPatrol.sqf";
call compile preprocessFileLineNumbers "AI\Group\GoalGroupRelax.sqf";
call compile preprocessFileLineNumbers "AI\Group\_SensorGroup.sqf";
call compile preprocessFileLineNumbers "AI\Group\_SensorGroupStimulatable.sqf";
call compile preprocessFileLineNumbers "AI\Group\SensorGroupHealth.sqf";
call compile preprocessFileLineNumbers "AI\Group\SensorGroupTargets.sqf";
call compile preprocessFileLineNumbers "AI\Group\initDatabase.sqf";
