#include "..\common.hpp"

ADD_LOADOUT("LOP_IRA_CIVILIAN_1",			"LOP_IRA_CIVILIAN\LOP_IRA_CIVILIAN_1.sqf")
ADD_LOADOUT("LOP_IRA_CIVILIAN_Militant_1",	"LOP_IRA_CIVILIAN\LOP_IRA_Militant_1.sqf")
ADD_LOADOUT("LOP_IRA_CIVILIAN_Saboteur_1",	"LOP_IRA_CIVILIAN\LOP_IRA_Saboteur_1.sqf")
ADD_LOADOUT("LOP_IRA_PLAYER_1",				"LOP_IRA_CIVILIAN\LOP_IRA_PLAYER_1.sqf")