#include "..\common.hpp"

ADD_LOADOUT("3CB_CCIVS_CIVILIAN_1",			"3CB_CCIVS\3CB_CCIVS_CIVILIAN_1.sqf")
ADD_LOADOUT("3CB_CCIVS_CIVILIAN_Militant_1",	"3CB_CCIVS\3CB_CCIVS_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("3CB_CCIVS_CIVILIAN_Saboteur_1",	"3CB_CCIVS\3CB_CCIVS_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("3CB_CCIVS_PLAYER_1",				"3CB_CCIVS\3CB_CCIVS_PLAYER_1.sqf")