#include "..\common.hpp"

ADD_LOADOUT("CUP_RUS_CIVILIAN_1",			"CUP_RUS_CIVILIAN\CUP_CIVILIAN_1.sqf")
ADD_LOADOUT("CUP_RUS_CIVILIAN_Militant_1",	"CUP_RUS_CIVILIAN\CUP_Militant_1.sqf")
ADD_LOADOUT("CUP_RUS_CIVILIAN_Saboteur_1",	"CUP_RUS_CIVILIAN\CUP_Saboteur_1.sqf")
ADD_LOADOUT("CUP_RUS_PLAYER_1",				"CUP_RUS_CIVILIAN\CUP_PLAYER_1.sqf")