#define CMDR_ACTION_STATE_NONE		-1000
#define CMDR_ACTION_STATE_START 	0
#define CMDR_ACTION_STATE_END 		1
#define CMDR_ACTION_STATE_ALL 		-1
#define CMDR_ACTION_STATE_CUSTOM	1000

#define CMDR_ACTION_PRIOR_TOP 		0
#define CMDR_ACTION_PRIOR_HIGH 		1
#define CMDR_ACTION_PRIOR_LOW 		10