#include "..\common.hpp"

ADD_LOADOUT("CUP_TKA_CIVILIAN_1",			"CUP_TKA_CIVILIAN\CUP_CIVILIAN_1.sqf")
ADD_LOADOUT("CUP_TKA_CIVILIAN_Militant_1",	"CUP_TKA_CIVILIAN\CUP_Militant_1.sqf")
ADD_LOADOUT("CUP_TKA_CIVILIAN_Saboteur_1",	"CUP_TKA_CIVILIAN\CUP_Saboteur_1.sqf")
ADD_LOADOUT("CUP_TKA_PLAYER_1",				"CUP_TKA_CIVILIAN\CUP_PLAYER_1.sqf")