removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

_RandomHeadgear = selectRandom ["rhs_6b47_ess","rhs_6b47","rhs_6b47_bala","rhs_6b47_ess_bala"];
this addHeadgear _RandomHeadgear;
this forceAddUniform "rhs_uniform_gorka_r_g";
this addVest "rhs_6b13_EMR_6sh92_vog";
this addBackpack "rhs_sidor";

this addWeapon "rhs_weap_ak74mr_gp25";
this addPrimaryWeaponItem "rhs_acc_tgpa";
this addPrimaryWeaponItem "rhs_VOG25";
_RandomSight = selectRandom ["rhs_acc_rakursPM", "rhs_acc_1p87", "rhs_acc_ekp8_18"];
this addPrimaryWeaponItem _RandomSight;
this addPrimaryWeaponItem "rhs_acc_perst3_top";
this addPrimaryWeaponItem "rhs_30Rnd_545x39_7N10_AK";
this addWeapon "rhs_weap_pya";
this addHandgunItem "rhs_mag_9x19_17";
this addWeapon "rhs_pdu4";

this addItemToUniform "FirstAidKit";
for "_i" from 1 to 2 do {this addItemToUniform "rhs_mag_9x19_17";};
this addItemToUniform "O_R_IR_Grenade";
for "_i" from 1 to 6 do {this addItemToVest "rhs_30Rnd_545x39_7N22_AK";};
this addItemToVest "rhs_mag_rdg2_black";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_fakel";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_fakels";};
this addItemToVest "rhs_mag_rgn";
this addItemToVest "rhs_mag_rgo";
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_VG40TB";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_VG40MD";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_VOG25P";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_GRD40_Green";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_GRD40_Red";};
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "rhs_1PN138";