[
	"Wildfire Palace", 
	"Firestone", 
	"Off Our Land!", 
	"Remember the Alamo", 
	"The Vineyard Vindication", 
	"Bambo II Electric Boogaloo", 
	"The Homies Holidays", 
	"Boxer Rebellion", 
	"Real Estate Rebellion", 
	"The Wineyard Uprising", 
	"The Du-Rag rebellion", 
	"The Goat conflict", 
	"The Cotton mutiny", 
	"The Irish War Of Independence", 
	"The Woolly Rebellion", 
	"James Rebellion", 
	"Tairngreacht Bas", 
	"The Yellow Yeezy Uprising", 
	"The Tea Crysis", 
	"Stavrou's dream", 
	"The Tzatziki Rebellion", 
	"The Pee Men", 
	"Friends of Spartacus", 
	"The Sparker in the Haybale", 
	"The Easter Rising", 
	"The IEDs of March", 
	"Organized Revolt", 
	"Straight-Up Murderfest", 
	"The QRFs from the North", 
	"BLU Man Group", 
	"Brown Death", 
	"The Coffee Revolution", 
	"No Step on Snek", 
	"Gladio", 
	"Stay Behind", 
	"IDAP 2", 
	"Confucian Conflict", 
	"Enduring Freedom", 
	"Health!", 
	"Kill 'em All", 
	"YEEEET!", 
	"Mass Confusion", 
	"Large Ice House", 
	"Just Cause", 
	"Eskimo Coat Factory Springtime Shindig", 
	"Yttrium Iodine Fluorine Fluorine", 
	"Totally Real Revolution",
	"The Boys from the Woods",
	"Fenian Rising",
	"The Second War of the Bucket",
	"Changing of the Guard"
]