#include "..\common.hpp"

ADD_LOADOUT("3CB_TCIV_CIVILIAN_1",			"3CB_TCIV\3CB_TCIV_CIVILIAN_1.sqf")
ADD_LOADOUT("3CB_TCIV_CIVILIAN_Militant_1",	"3CB_TCIV\3CB_TCIV_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("3CB_TCIV_CIVILIAN_Saboteur_1",	"3CB_TCIV\3CB_TCIV_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("3CB_TCIV_PLAYER_1",				"3CB_TCIV\3CB_TCIV_PLAYER_1.sqf")