#include "..\common.hpp"

ADD_LOADOUT("SPE_CIVILIAN_Default",		"SPE_CIVILIAN\SPE_CIVILIAN_Default.sqf")
ADD_LOADOUT("SPE_CIVILIAN_1",			"SPE_CIVILIAN\SPE_CIVILIAN_1.sqf")
ADD_LOADOUT("SPE_CIVILIAN_Militant_1",	"SPE_CIVILIAN\SPE_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("SPE_CIVILIAN_Saboteur_1",	"SPE_CIVILIAN\SPE_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("SPE_PLAYER_1",				"SPE_CIVILIAN\SPE_PLAYER_1.sqf")
