#include "..\common.hpp"

ADD_LOADOUT("VN_CIVILIAN_Default",		"VN_CIVILIAN\VN_CIVILIAN_Default.sqf")
ADD_LOADOUT("VN_CIVILIAN_1",			"VN_CIVILIAN\VN_CIVILIAN_1.sqf")
ADD_LOADOUT("VN_CIVILIAN_Militant_1",	"VN_CIVILIAN\VN_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("VN_CIVILIAN_Saboteur_1",	"VN_CIVILIAN\VN_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("VN_PLAYER_1",				"VN_CIVILIAN\VN_PLAYER_1.sqf")
