#include "..\..\common.hpp"

ADD_LOADOUT("GM_WG_AmmoBearer",	 "GM_WestGer\WestGer\GM_WG_AmmoBearer.sqf")
ADD_LOADOUT("GM_WG_ArmyOfficer", "GM_WestGer\WestGer\GM_WG_ArmyOfficer.sqf")
ADD_LOADOUT("GM_WG_AT", 		 "GM_WestGer\WestGer\GM_WG_AT.sqf")
ADD_LOADOUT("GM_WG_Crew",	 	 "GM_WestGer\WestGer\GM_WG_Crew.sqf")
ADD_LOADOUT("GM_WG_Demolition",	 "GM_WestGer\WestGer\GM_WG_Demolition.sqf")
ADD_LOADOUT("GM_WG_Engineer",    "GM_WestGer\WestGer\GM_WG_Engineer.sqf")
ADD_LOADOUT("GM_WG_LAT",	     "GM_WestGer\WestGer\GM_WG_LAT.sqf")
ADD_LOADOUT("GM_WG_Marksman",	 "GM_WestGer\WestGer\GM_WG_Marksman.sqf")
ADD_LOADOUT("GM_WG_Medic", 		 "GM_WestGer\WestGer\GM_WG_Medic.sqf")
ADD_LOADOUT("GM_WG_MG", 		 "GM_WestGer\WestGer\GM_WG_MG.sqf")
ADD_LOADOUT("GM_WG_Rifleman", 	 "GM_WestGer\WestGer\GM_WG_Rifleman.sqf")
ADD_LOADOUT("GM_WG_SL", 		 "GM_WestGer\WestGer\GM_WG_SL.sqf")
ADD_LOADOUT("GM_WG_Unarmed", 	 "GM_WestGer\WestGer\GM_WG_Unarmed.sqf")