removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this addHeadgear "rhsgref_helmet_pasgt_flecktarn";
_RandomGoggles = selectRandom ["G_Balaclava_blk", "G_Bandanna_blk"];
this addGoggles _RandomGoggles;
_RandomVest = selectRandom ["V_TacVestIR_blk", "V_Chestrig_blk"];
this addVest _RandomVest;
this forceAddUniform "rhsgref_uniform_gorka_1_f";
this addBackpack "B_TacticalPack_blk";

this addWeapon "rhs_weap_SCARH_STD";
_RandomSight = selectRandom ["rhsusf_acc_su230a", "rhsusf_acc_su230a_mrds"];
this addPrimaryWeaponItem _RandomSight;
_RandomGrip = selectRandom ["rhsusf_acc_grip2", "rhsusf_acc_grip1", ""];
this addPrimaryWeaponItem _RandomGrip;
this addPrimaryWeaponItem "rhsusf_acc_aac_762sd_silencer";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk";
this addWeapon "rhs_weap_M320";
this addHandgunItem "rhs_mag_M433_HEDP";
this addWeapon "rhsusf_bino_lrf_Vector21";
this addWeapon "rhs_weap_M136_hedp";

this addItemToUniform "FirstAidKit";
this addItemToUniform "B_IR_Grenade";
for "_i" from 1 to 4 do {this addItemToUniform "rhs_mag_mk84";};
for "_i" from 1 to 6 do {this addItemToVest "rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_20Rnd_SCAR_762x51_m62_tracer_bk";};
for "_i" from 1 to 10 do {this addItemToBackpack "rhs_mag_M433_HEDP";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m4009";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m576";};
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_M585_white";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m714_White";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_M397_HET";};
this addItemToBackpack "rhs_mag_an_m8hc";
this addItemToBackpack "rhs_mag_m18_yellow";
this addItemToBackpack "rhs_mag_m18_red";
this addItemToBackpack "rhs_mag_m18_purple";
this addItemToBackpack "rhs_mag_m18_green";
this addItemToBackpack "rhs_mag_an_m14_th3";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "rhsusf_ANPVS_15";