removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

_RandomHeadgear = selectRandom ["H_Booniehat_oli","rhsusf_opscore_fg","rhsusf_opscore_fg_pelt","rhsusf_opscore_fg_pelt_cam"];
this addHeadgear _RandomHeadgear;
_RandomGoggles = selectRandom ["G_Bandanna_oli", "rhsusf_shemagh_grn", "rhsusf_shemagh2_grn", "rhsusf_shemagh_gogg_grn", "rhsusf_shemagh2_gogg_grn", "", ""];
this addGoggles _RandomGoggles;
this forceAddUniform "mnaf_lizardo";
this addVest "V_CarrierRigKBT_01_heavy_Olive_F";
this addBackpack "B_FieldPack_oli";

this addWeapon "rhs_weap_SCARH_STD";
_RandomSight = selectRandom ["rhsusf_acc_su230a", "rhsusf_acc_su230a_mrds", "rhsusf_acc_eotech_xps3", "rhsusf_acc_g33_xps3"];
this addPrimaryWeaponItem _RandomSight;
_RandomGrip = selectRandom ["rhsusf_acc_grip2", "rhsusf_acc_kac_grip", "rhsusf_acc_grip1", ""];
this addPrimaryWeaponItem _RandomGrip;
this addPrimaryWeaponItem "rhsusf_acc_aac_762sd_silencer";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15side_bk";
this addPrimaryWeaponItem "rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk";
this addWeapon "rhs_weap_m72a7";
this addWeapon "rhs_weap_M320";
this addHandgunItem "rhs_mag_M433_HEDP";
this addWeapon "rhsusf_bino_lrf_Vector21";

this addItemToUniform "FirstAidKit";
this addItemToUniform "B_IR_Grenade";
for "_i" from 1 to 6 do {this addItemToVest "rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_mk84";};
for "_i" from 1 to 10 do {this addItemToBackpack "rhs_mag_M433_HEDP";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m4009";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m576";};
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_M585_white";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m714_White";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_M397_HET";};
this addItemToBackpack "rhs_mag_an_m8hc";
this addItemToBackpack "rhs_mag_m18_yellow";
this addItemToBackpack "rhs_mag_m18_red";
this addItemToBackpack "rhs_mag_m18_purple";
this addItemToBackpack "rhs_mag_m18_green";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles_OPFOR";