#include "..\..\common.hpp"

ADD_LOADOUT("RHS_POLICE_1",		"RHS_APD\Police\RHS_POLICE_(1).sqf")
ADD_LOADOUT("RHS_POLICE_2",		"RHS_APD\Police\RHS_POLICE_(2).sqf")
ADD_LOADOUT("RHS_POLICE_3",		"RHS_APD\Police\RHS_POLICE_(3).sqf")
ADD_LOADOUT("RHS_POLICE_4",		"RHS_APD\Police\RHS_POLICE_(4).sqf")
ADD_LOADOUT("RHS_POLICE_5",		"RHS_APD\Police\RHS_POLICE_(5).sqf")
ADD_LOADOUT("RHS_POLICE_6",		"RHS_APD\Police\RHS_POLICE_(6).sqf")
ADD_LOADOUT("RHS_POLICE_7",		"RHS_APD\Police\RHS_POLICE_(7).sqf")
ADD_LOADOUT("RHS_POLICE_8",		"RHS_APD\Police\RHS_POLICE_(8).sqf")
ADD_LOADOUT("RHS_POLICE_9",		"RHS_APD\Police\RHS_POLICE_(9).sqf")
ADD_LOADOUT("RHS_POLICE_10",	"RHS_APD\Police\RHS_POLICE_(10).sqf")


