// Auto generated file
call compile preprocessFileLineNumbers "AI\Unit\AIUnit.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitDismountCurrentVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitGetInVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitMoveToDanger.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitScareAway.sqf";
call compile preprocessFileLineNumbers "AI\Unit\GoalUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\GoalUnitScareAway.sqf";
call compile preprocessFileLineNumbers "AI\Unit\SensorUnitCivNear.sqf";
call compile preprocessFileLineNumbers "AI\Unit\SensorUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\initDatabase.sqf";
