// Auto generated file
call compile preprocessFileLineNumbers "AI\Unit\AIUnitInfantry.sqf";
call compile preprocessFileLineNumbers "AI\Unit\AIUnitVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\_ActionUnit.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitDismountCurrentVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitGetInVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\ActionUnitScareAway.sqf";
call compile preprocessFileLineNumbers "AI\Unit\GoalUnitGetInVehicle.sqf";
call compile preprocessFileLineNumbers "AI\Unit\GoalUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\GoalUnitScareAway.sqf";
call compile preprocessFileLineNumbers "AI\Unit\_SensorUnit.sqf";
call compile preprocessFileLineNumbers "AI\Unit\_SensorUnitStimulatable.sqf";
call compile preprocessFileLineNumbers "AI\Unit\SensorUnitCivNear.sqf";
call compile preprocessFileLineNumbers "AI\Unit\SensorUnitSalute.sqf";
call compile preprocessFileLineNumbers "AI\Unit\initDatabase.sqf";
