#include "..\UI_OOP\oop.h"
CLASS("oo_UIUndercoverDebug")

	PRIVATE UI_VARIABLE("control", "MainLayer");
	PRIVATE UI_VARIABLE("control", "OOP_MainLayer_100");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Blank");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_BodyExp");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Captive");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Distance");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_InVeh");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_InVehCiv");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_InVehMil");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_LastSpottedTimes");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Seen");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Susp");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_SuspGear");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_SuspGear_0_0");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Suspicious");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_SuspVeh");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_TimeUnseen");
	PRIVATE UI_VARIABLE("control", "OOP_Text_101_Wanted");
	PRIVATE UI_VARIABLE("display", "Display");

	PUBLIC FUNCTION("display", "constructor"){
		disableSerialization;
		MEMBER("Display", _this);
		MEMBER("MainLayer", _this displayCtrl 100);
		MEMBER("OOP_MainLayer_100", _this displayCtrl 100);
		MEMBER("OOP_Text_101_Blank", _this displayCtrl 117);
		MEMBER("OOP_Text_101_BodyExp", _this displayCtrl 115);
		MEMBER("OOP_Text_101_Captive", _this displayCtrl 108);
		MEMBER("OOP_Text_101_Distance", _this displayCtrl 106);
		MEMBER("OOP_Text_101_InVeh", _this displayCtrl 110);
		MEMBER("OOP_Text_101_InVehCiv", _this displayCtrl 114);
		MEMBER("OOP_Text_101_InVehMil", _this displayCtrl 111);
		MEMBER("OOP_Text_101_LastSpottedTimes", _this displayCtrl 116);
		MEMBER("OOP_Text_101_Seen", _this displayCtrl 105);
		MEMBER("OOP_Text_101_Susp", _this displayCtrl 101);
		MEMBER("OOP_Text_101_SuspGear", _this displayCtrl 102);
		MEMBER("OOP_Text_101_SuspGear_0_0", _this displayCtrl 113);
		MEMBER("OOP_Text_101_Suspicious", _this displayCtrl 104);
		MEMBER("OOP_Text_101_SuspVeh", _this displayCtrl 112);
		MEMBER("OOP_Text_101_TimeUnseen", _this displayCtrl 107);
		MEMBER("OOP_Text_101_Wanted", _this displayCtrl 103);
		MEMBER("Init", nil);
	};
	PUBLIC FUNCTION("", "Init"){
		//Add your content here to init display
	};
	PUBLIC FUNCTION("", "getDisplay") FUNC_GETVAR("Display");
	PUBLIC FUNCTION("", "getMainLayer") FUNC_GETVAR("MainLayer");
	PUBLIC FUNCTION("", "getOOP_MainLayer_100") FUNC_GETVAR("OOP_MainLayer_100");
	PUBLIC FUNCTION("", "getOOP_Text_101_Blank") FUNC_GETVAR("OOP_Text_101_Blank");
	PUBLIC FUNCTION("", "getOOP_Text_101_BodyExp") FUNC_GETVAR("OOP_Text_101_BodyExp");
	PUBLIC FUNCTION("", "getOOP_Text_101_Captive") FUNC_GETVAR("OOP_Text_101_Captive");
	PUBLIC FUNCTION("", "getOOP_Text_101_Distance") FUNC_GETVAR("OOP_Text_101_Distance");
	PUBLIC FUNCTION("", "getOOP_Text_101_InVeh") FUNC_GETVAR("OOP_Text_101_InVeh");
	PUBLIC FUNCTION("", "getOOP_Text_101_InVehCiv") FUNC_GETVAR("OOP_Text_101_InVehCiv");
	PUBLIC FUNCTION("", "getOOP_Text_101_InVehMil") FUNC_GETVAR("OOP_Text_101_InVehMil");
	PUBLIC FUNCTION("", "getOOP_Text_101_LastSpottedTimes") FUNC_GETVAR("OOP_Text_101_LastSpottedTimes");
	PUBLIC FUNCTION("", "getOOP_Text_101_Seen") FUNC_GETVAR("OOP_Text_101_Seen");
	PUBLIC FUNCTION("", "getOOP_Text_101_Susp") FUNC_GETVAR("OOP_Text_101_Susp");
	PUBLIC FUNCTION("", "getOOP_Text_101_SuspGear") FUNC_GETVAR("OOP_Text_101_SuspGear");
	PUBLIC FUNCTION("", "getOOP_Text_101_SuspGear_0_0") FUNC_GETVAR("OOP_Text_101_SuspGear_0_0");
	PUBLIC FUNCTION("", "getOOP_Text_101_Suspicious") FUNC_GETVAR("OOP_Text_101_Suspicious");
	PUBLIC FUNCTION("", "getOOP_Text_101_SuspVeh") FUNC_GETVAR("OOP_Text_101_SuspVeh");
	PUBLIC FUNCTION("", "getOOP_Text_101_TimeUnseen") FUNC_GETVAR("OOP_Text_101_TimeUnseen");
	PUBLIC FUNCTION("", "getOOP_Text_101_Wanted") FUNC_GETVAR("OOP_Text_101_Wanted");
	PUBLIC FUNCTION("control", "setMainLayer"){ MEMBER("MainLayer", _this); };
	PUBLIC FUNCTION("control", "setOOP_MainLayer_100"){ MEMBER("OOP_MainLayer_100", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Blank"){ MEMBER("OOP_Text_101_Blank", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_BodyExp"){ MEMBER("OOP_Text_101_BodyExp", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Captive"){ MEMBER("OOP_Text_101_Captive", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Distance"){ MEMBER("OOP_Text_101_Distance", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_InVeh"){ MEMBER("OOP_Text_101_InVeh", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_InVehCiv"){ MEMBER("OOP_Text_101_InVehCiv", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_InVehMil"){ MEMBER("OOP_Text_101_InVehMil", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_LastSpottedTimes"){ MEMBER("OOP_Text_101_LastSpottedTimes", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Seen"){ MEMBER("OOP_Text_101_Seen", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Susp"){ MEMBER("OOP_Text_101_Susp", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_SuspGear"){ MEMBER("OOP_Text_101_SuspGear", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_SuspGear_0_0"){ MEMBER("OOP_Text_101_SuspGear_0_0", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Suspicious"){ MEMBER("OOP_Text_101_Suspicious", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_SuspVeh"){ MEMBER("OOP_Text_101_SuspVeh", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_TimeUnseen"){ MEMBER("OOP_Text_101_TimeUnseen", _this); };
	PUBLIC FUNCTION("control", "setOOP_Text_101_Wanted"){ MEMBER("OOP_Text_101_Wanted", _this); };
	PUBLIC FUNCTION("display", "setDisplay"){ MEMBER("Display", _this); };
	PUBLIC FUNCTION("", "deconstructor"){
		DELETE_UI_VARIABLE("MainLayer");
		DELETE_UI_VARIABLE("OOP_MainLayer_100");
		DELETE_UI_VARIABLE("OOP_Text_101_Blank");
		DELETE_UI_VARIABLE("OOP_Text_101_BodyExp");
		DELETE_UI_VARIABLE("OOP_Text_101_Captive");
		DELETE_UI_VARIABLE("OOP_Text_101_Distance");
		DELETE_UI_VARIABLE("OOP_Text_101_InVeh");
		DELETE_UI_VARIABLE("OOP_Text_101_InVehCiv");
		DELETE_UI_VARIABLE("OOP_Text_101_InVehMil");
		DELETE_UI_VARIABLE("OOP_Text_101_LastSpottedTimes");
		DELETE_UI_VARIABLE("OOP_Text_101_Seen");
		DELETE_UI_VARIABLE("OOP_Text_101_Susp");
		DELETE_UI_VARIABLE("OOP_Text_101_SuspGear");
		DELETE_UI_VARIABLE("OOP_Text_101_SuspGear_0_0");
		DELETE_UI_VARIABLE("OOP_Text_101_Suspicious");
		DELETE_UI_VARIABLE("OOP_Text_101_SuspVeh");
		DELETE_UI_VARIABLE("OOP_Text_101_TimeUnseen");
		DELETE_UI_VARIABLE("OOP_Text_101_Wanted");
		DELETE_UI_VARIABLE("Display");
	};
ENDCLASS;
