#include "..\common.hpp"

ADD_LOADOUT("WW2_CIVILIAN_Default",		"WW2_CIVILIAN\WW2_CIVILIAN_Default.sqf")
ADD_LOADOUT("WW2_CIVILIAN_1",			"WW2_CIVILIAN\WW2_CIVILIAN_1.sqf")
ADD_LOADOUT("WW2_CIVILIAN_Militant_1",	"WW2_CIVILIAN\WW2_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("WW2_CIVILIAN_Saboteur_1",	"WW2_CIVILIAN\WW2_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("WW2_PLAYER_1",				"WW2_CIVILIAN\WW2_PLAYER_1.sqf")
