// States of a goal
#define ACTION_STATE_ACTIVE		0
#define ACTION_STATE_INACTIVE	1
#define ACTION_STATE_COMPLETED	2
#define ACTION_STATE_FAILED		3

#define ACTION_STATE_TEXT_ARRAY ["ACTIVE", "INACTIVE", "COMPLETED", "FAILED"]