gCombatTips = [
	"Always wear a helmet, even at base!",
	"Have you checked your ammo?",
	"Stay alert when on patrol!",
	"Ensure your radio frequency and channel!",
	"Never do a selfie in fight!",
	"Remember to stay in formation, ... but not too close!",
	"Remember to check fuel of your vehicles!",
	"Find your gun safety switch before fight!",
    "Don't text while driving your tank.",
    "Don't confuse concealment with cover.",
    "Don't stand in the backblast area.",
    "Tracers work both ways.",
    "Drive with caution when approaching wired fences.",
    "Morphine will definitely cure everything.",
    "If you think the enemy is dead then shoot them again.",
    "Repeated use of strange pills is not recommended.",
    "If they move, they're an enemy. If they don't move, they're a well trained enemy.",
    "Remember, that bush may have a sniper in it.",
    "Keep with you a long rifle and a friend with a long rifle.",
    "Don't aim at anything you don't intend to liberate!",
    "If it's dark, bring nightvision. If you don't have nightvision, bring a flashlight. If you don't have a flashlight, bring some carrots.",
    "Don't eat yellow snow and don't chew on blasting caps.",
    "Do not confuse your C4 and your MRE, C4 is also not to be used as Playdough.",
    "Friendly Fire is never friendly.",
    "Everything is amphibious once.",
    "Bridges are more hazardous than they first appear.",
    "If your gun jams, then start eating marmalade.",
    "If at first you don't succeed, deploy mortars.",
    "Enemy armor is never just 'Passing By'.",
    "Unnecessary violence against backpackers has been approved.",
    "If you forget your gun, remember that your friend's gun is a good replacement.",
    "If in doubt, shoot one out.",
    "Do not stay behind AT and AA ... and also not in front.",
    "Once the pin is pulled, Mr. Grenade is no longer your friend.",
    "A grenade is not medical equipment.",
    "The enemy is not responsible for your ammo.",
    "Don't let the enemy capture your artillery.",
    "Carry a few liters of blood, it doesn't have to be yours.",
    "If your mate is down, clear the area first, patch him up later.",
    "One soldier dead is better than 2 dead to save 1.",
    "Please disable adblock to see the tip of the day.",
    "(todo: insert random quote from the Art of War)",
    "This content is not available in your country!",
    "A Crayon will burn for 30 Minutes in an emergency, two when it is being tested.",
    "Don’t poach a tank, they are better fried.",
    "Don’t leave your armored vehicle when getting shot at!",
    "If in doubt, frag out.",
    "Poor driving from civilians does not constitute hostile fire -- unless they hit someone.",
    "Approach civilians carefully they might have bombs on them - or other strange substances.",
    "It is not advised to take strange pills and drive!",
    "Your cousin might be out there fighting dragons, but you have guard duty!",
    "All furniture requisition forms will be denied.",
    "Hop like a butterfly, and sting like a bee.",
    "Point the end of the barrel at the enemy. Not the other way around.",
    "Applying a tourniquet to the neck is only to be done for medical purposes, or with someone you trust."
];