#include "..\..\common.hpp"

ADD_LOADOUT("WW2_Heer_engineer",	"WW2_Heer\Heer\Heer_engineer.sqf")
ADD_LOADOUT("WW2_Heer_LMG",			"WW2_Heer\Heer\Heer_LMG.sqf")
ADD_LOADOUT("WW2_Heer_LMG_2",		"WW2_Heer\Heer\Heer_LMG_2.sqf")
ADD_LOADOUT("WW2_Heer_HMG",			"WW2_Heer\Heer\Heer_HMG.sqf")
ADD_LOADOUT("WW2_Heer_rifleman",	"WW2_Heer\Heer\Heer_rifleman.sqf")
ADD_LOADOUT("WW2_Heer_rifleman_2",	"WW2_Heer\Heer\Heer_rifleman_2.sqf")
ADD_LOADOUT("WW2_Heer_rifleman_3",	"WW2_Heer\Heer\Heer_rifleman_3.sqf")
ADD_LOADOUT("WW2_Heer_rifleman_4",	"WW2_Heer\Heer\Heer_rifleman_4.sqf")
ADD_LOADOUT("WW2_Heer_rifleman_5",	"WW2_Heer\Heer\Heer_rifleman_5.sqf")
ADD_LOADOUT("WW2_Heer_spotter",		"WW2_Heer\Heer\Heer_spotter.sqf")
ADD_LOADOUT("WW2_Heer_ammo",		"WW2_Heer\Heer\Heer_ammo.sqf")
ADD_LOADOUT("WW2_Heer_unarmed",		"WW2_Heer\Heer\Heer_unarmed.sqf")
ADD_LOADOUT("WW2_Heer_AT",			"WW2_Heer\Heer\Heer_AT.sqf")
ADD_LOADOUT("WW2_Heer_explosives",	"WW2_Heer\Heer\Heer_explosives.sqf")